//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryForecast.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalaryForecast.Core.Resources.LocalizableResources", typeof(LocalizableResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Доп. расходы/
        ///       премии .
        /// </summary>
        internal static string AdditionalPay {
            get {
                return ResourceManager.GetString("AdditionalPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные платежи.
        /// </summary>
        internal static string AdditionalPays {
            get {
                return ResourceManager.GetString("AdditionalPays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица дополнительных платежей.
        /// </summary>
        internal static string AdditionalPayTable {
            get {
                return ResourceManager.GetString("AdditionalPayTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый платёж.
        /// </summary>
        internal static string AddNewPay {
            get {
                return ResourceManager.GetString("AddNewPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апрель.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Август.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассчётный остаток:.
        /// </summary>
        internal static string CalculatedMoney {
            get {
                return ResourceManager.GetString("CalculatedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассчётное значение:.
        /// </summary>
        internal static string CalculatedValue {
            get {
                return ResourceManager.GetString("CalculatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует файл производственного календаря на текущий или предыдущий год. Расчёт остановлен..
        /// </summary>
        internal static string CalendarDoesNotExists {
            get {
                return ResourceManager.GetString("CalendarDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        internal static string CommentHeader {
            get {
                return ResourceManager.GetString("CommentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корректировка фактического значения остатков после выплат {0:M}.
        /// </summary>
        internal static string Correction {
            get {
                return ResourceManager.GetString("Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорректировать по реальному значению.
        /// </summary>
        internal static string CorrectRealValue {
            get {
                return ResourceManager.GetString("CorrectRealValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий год.
        /// </summary>
        internal static string CurrentYear {
            get {
                return ResourceManager.GetString("CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные автоматически сохранятся и главная таблица
        ///    автоматически будет пересчитана после того как 
        ///                      данное окно будет закрыто.
        /// </summary>
        internal static string DataWillBeUpdatedAfterClosing {
            get {
                return ResourceManager.GetString("DataWillBeUpdatedAfterClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные автоматически сохранятся и главная таблица автоматически будет пересчитана 
        ///                                  после того как данное окно будет закрыто.
        /// </summary>
        internal static string DataWillBeUpdatedAfterClosingWide {
            get {
                return ResourceManager.GetString("DataWillBeUpdatedAfterClosingWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Дата
        ///выплаты.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дней.
        /// </summary>
        internal static string daysMany {
            get {
                return ResourceManager.GetString("daysMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дня.
        /// </summary>
        internal static string daysSeveral {
            get {
                return ResourceManager.GetString("daysSeveral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to день.
        /// </summary>
        internal static string daysSingle {
            get {
                return ResourceManager.GetString("daysSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декабрь.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать таблицу дополнительных платежей.
        /// </summary>
        internal static string EditAdditionalPays {
            get {
                return ResourceManager.GetString("EditAdditionalPays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Февраль.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проведён.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличные с зарплаты, руб..
        /// </summary>
        internal static string FirstCash {
            get {
                return ResourceManager.GetString("FirstCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер денежных средств, которые обязательно
        ///нужно снять в день зарплаты. Например, на оплату
        ///питания, проезда. Сюда не входят платежи по займам
        ///и кредитам..
        /// </summary>
        internal static string FirstCashToolTip {
            get {
                return ResourceManager.GetString("FirstCashToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число выплаты зарплаты:.
        /// </summary>
        internal static string FirstPartDate {
            get {
                return ResourceManager.GetString("FirstPartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День выплаты зарплаты. Если день выпадает на
        ///выходной или праздничный день, рассчитывется
        ///ближайший к нему предыдущий рабочий день.
        /// </summary>
        internal static string FirstPartDateToolTip {
            get {
                return ResourceManager.GetString("FirstPartDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплаты с зарплаты, руб..
        /// </summary>
        internal static string FirstPay {
            get {
                return ResourceManager.GetString("FirstPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер платежей по займам и кредитам, 
        ///которые делаются после получения зарплаты..
        /// </summary>
        internal static string FirstPayToolTip {
            get {
                return ResourceManager.GetString("FirstPayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зелёным.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  подсвечивается строка ближайшей выплаты.
        /// </summary>
        internal static string GreenHelp {
            get {
                return ResourceManager.GetString("GreenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красно-зелёным.
        /// </summary>
        internal static string GreenRed {
            get {
                return ResourceManager.GetString("GreenRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  подсвечивается строка аванса, если в этом месяце имеется отрицательный баланс, то есть все доходы месяца меньше всех расходов и этот аванс является ближайшей выплатой.
        /// </summary>
        internal static string GreenRedHelp {
            get {
                return ResourceManager.GetString("GreenRedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Январь.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июль.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июнь.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Март.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальные траты.
        /// </summary>
        internal static string MaxDiscount {
            get {
                return ResourceManager.GetString("MaxDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальные траты
        ///(альтернатива).
        /// </summary>
        internal static string MaxDiscountAlternative {
            get {
                return ResourceManager.GetString("MaxDiscountAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Май.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месяц.
        /// </summary>
        internal static string MonthHeader {
            get {
                return ResourceManager.GetString("MonthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До следующей зарплаты осталось.
        /// </summary>
        internal static string NextSalaryDays {
            get {
                return ResourceManager.GetString("NextSalaryDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноябрь.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Октябрь.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потери от одного
        ///      дня отгула.
        /// </summary>
        internal static string OneDayCost {
            get {
                return ResourceManager.GetString("OneDayCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Монетизация&quot;
        ///    выходных.
        /// </summary>
        internal static string OneHolidayCost {
            get {
                return ResourceManager.GetString("OneHolidayCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Часть 
        ///платежа.
        /// </summary>
        internal static string PartHeader {
            get {
                return ResourceManager.GetString("PartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платёж.
        /// </summary>
        internal static string PayHeader {
            get {
                return ResourceManager.GetString("PayHeader", resourceCulture);
            }
        }

        internal static string PayTypeHeader {
            get {
                return ResourceManager.GetString("PayTypeHeader", resourceCulture);
            }
        }

        internal static string PayTypeExpense {
            get {
                return ResourceManager.GetString("PayTypeExpense", resourceCulture);
            }
        }

        internal static string PayTypeIncome {
            get {
                return ResourceManager.GetString("PayTypeIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Величина выплаты, руб..
        /// </summary>
        internal static string PaymentAmount {
            get {
                return ResourceManager.GetString("PaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата платежа.
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование платежа.
        /// </summary>
        internal static string PaymentName {
            get {
                return ResourceManager.GetString("PaymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остаток на
        ///конец периода.
        /// </summary>
        internal static string PeriodBalance {
            get {
                return ResourceManager.GetString("PeriodBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остаток на конец
        ///периода (альтернатива).
        /// </summary>
        internal static string PeriodBalanceAlternative {
            get {
                return ResourceManager.GetString("PeriodBalanceAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий год.
        /// </summary>
        internal static string PreviousYear {
            get {
                return ResourceManager.GetString("PreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогноз зарплаты.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реальный остаток:.
        /// </summary>
        internal static string RealValue {
            get {
                return ResourceManager.GetString("RealValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красным.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  подсвечивается строка аванса, если в этом месяце имеется отрицательный баланс, то есть все доходы месяца меньше всех расходов.
        /// </summary>
        internal static string RedHelp {
            get {
                return ResourceManager.GetString("RedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выбранный платёж.
        /// </summary>
        internal static string RemoveSelectedPay {
            get {
                return ResourceManager.GetString("RemoveSelectedPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Месячная 
        ///разница, руб..
        /// </summary>
        internal static string SalaryDelta {
            get {
                return ResourceManager.GetString("SalaryDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аванс ({0}).
        /// </summary>
        internal static string SalaryPartAdvance {
            get {
                return ResourceManager.GetString("SalaryPartAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доля.
        /// </summary>
        internal static string SalaryPartPercent {
            get {
                return ResourceManager.GetString("SalaryPartPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарплата ({0}).
        /// </summary>
        internal static string SalaryPartSalary {
            get {
                return ResourceManager.GetString("SalaryPartSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Выплата.
        /// </summary>
        internal static string SalaryPartValue {
            get {
                return ResourceManager.GetString("SalaryPartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплата без
        ///  наличных.
        /// </summary>
        internal static string SalaryPartWithoutCash {
            get {
                return ResourceManager.GetString("SalaryPartWithoutCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки зарплаты.
        /// </summary>
        internal static string SalarySettings {
            get {
                return ResourceManager.GetString("SalarySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Величина зарплаты в месяц, руб.:.
        /// </summary>
        internal static string SalaryValue {
            get {
                return ResourceManager.GetString("SalaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер зарплаты в месяц
        ///за вычитом всех налогов.
        /// </summary>
        internal static string SalaryValueToolTip {
            get {
                return ResourceManager.GetString("SalaryValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остаток после
        ///всех платежей.
        /// </summary>
        internal static string SalaryWithoutCashAndPay {
            get {
                return ResourceManager.GetString("SalaryWithoutCashAndPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличные с аванса, руб..
        /// </summary>
        internal static string SecondCash {
            get {
                return ResourceManager.GetString("SecondCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер денежных средств, которые обязательно
        ///нужно снять в день аванса. Например, на оплату
        ///питания, проезда. Сюда не входят платежи по займам
        ///и кредитам..
        /// </summary>
        internal static string SecondCashToolTip {
            get {
                return ResourceManager.GetString("SecondCashToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число выплаты аванса:.
        /// </summary>
        internal static string SecondPartDate {
            get {
                return ResourceManager.GetString("SecondPartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День выплаты аванса. Если день выпадает на
        ///выходной или праздничный день, рассчитывется
        ///ближайший к нему предыдущий рабочий день.
        /// </summary>
        internal static string SecondPartDateToolTip {
            get {
                return ResourceManager.GetString("SecondPartDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплаты с аванса, руб..
        /// </summary>
        internal static string SecondPay {
            get {
                return ResourceManager.GetString("SecondPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер платежей по займам и кредитам, 
        ///которые делаются после получения аванса..
        /// </summary>
        internal static string SecondPayToolTip {
            get {
                return ResourceManager.GetString("SecondPayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сентябрь.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать/скрыть предыдущий год.
        /// </summary>
        internal static string ToggleLastYear {
            get {
                return ResourceManager.GetString("ToggleLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать/скрыть дополнительные данные.
        /// </summary>
        internal static string ToggleShortView {
            get {
                return ResourceManager.GetString("ToggleShortView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной
        ///расчёт.
        /// </summary>
        internal static string UseInCalculation {
            get {
                return ResourceManager.GetString("UseInCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входит в расчёт
        ///средней з/пл.
        /// </summary>
        internal static string UseInCalculationOfVacation {
            get {
                return ResourceManager.GetString("UseInCalculationOfVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешний вид.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! Внимание! Положительная величина платежа вводится для обозначения трат. 
        ///                Премии вводятся с отрицательной величиной платежа !!!
        ///Часть платежа - индекс от 1 до 2 выплаты:
        ///1 - зарплата (первая часть выплат в начале месяца);
        ///2 - аванс (вторая часть выплат в конце месяца)..
        /// </summary>
        internal static string WarningNegativePay {
            get {
                return ResourceManager.GetString("WarningNegativePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовой баланс, руб.:.
        /// </summary>
        internal static string YearBalance {
            get {
                return ResourceManager.GetString("YearBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовой баланс.
        /// </summary>
        internal static string YearBalanceHeader {
            get {
                return ResourceManager.GetString("YearBalanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовой баланс
        ///(альтернатива).
        /// </summary>
        internal static string YearBalanceSecondHeader {
            get {
                return ResourceManager.GetString("YearBalanceSecondHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        internal static string YearHeader {
            get {
                return ResourceManager.GetString("YearHeader", resourceCulture);
            }
        }
    }
}
