//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryForecast.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalaryForecast.Core.Resources.LocalizableResources", typeof(LocalizableResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий год.
        /// </summary>
        internal static string CurrentYear {
            get {
                return ResourceManager.GetString("CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выплаты.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дней.
        /// </summary>
        internal static string daysMany {
            get {
                return ResourceManager.GetString("daysMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дня.
        /// </summary>
        internal static string daysSeveral {
            get {
                return ResourceManager.GetString("daysSeveral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to день.
        /// </summary>
        internal static string daysSingle {
            get {
                return ResourceManager.GetString("daysSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличные с зарплаты, руб..
        /// </summary>
        internal static string FirstCash {
            get {
                return ResourceManager.GetString("FirstCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число выплаты зарплаты:.
        /// </summary>
        internal static string FirstPartDate {
            get {
                return ResourceManager.GetString("FirstPartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплаты с зарплаты, руб..
        /// </summary>
        internal static string FirstPay {
            get {
                return ResourceManager.GetString("FirstPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До следующей зарплаты осталось.
        /// </summary>
        internal static string NextSalaryDays {
            get {
                return ResourceManager.GetString("NextSalaryDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий год.
        /// </summary>
        internal static string PreviousYear {
            get {
                return ResourceManager.GetString("PreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предсказатель зарплаты.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месячная разница, руб..
        /// </summary>
        internal static string SalaryDelta {
            get {
                return ResourceManager.GetString("SalaryDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % от зарплаты.
        /// </summary>
        internal static string SalaryPartPercent {
            get {
                return ResourceManager.GetString("SalaryPartPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплата, руб..
        /// </summary>
        internal static string SalaryPartValue {
            get {
                return ResourceManager.GetString("SalaryPartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплата без наличных, руб..
        /// </summary>
        internal static string SalaryPartWithoutCash {
            get {
                return ResourceManager.GetString("SalaryPartWithoutCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки зарплаты.
        /// </summary>
        internal static string SalarySettings {
            get {
                return ResourceManager.GetString("SalarySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Величина зарплаты в месяц, руб.:.
        /// </summary>
        internal static string SalaryValue {
            get {
                return ResourceManager.GetString("SalaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остаток после всех платежей, руб..
        /// </summary>
        internal static string SalaryWithoutCashAndPay {
            get {
                return ResourceManager.GetString("SalaryWithoutCashAndPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличные с аванса, руб..
        /// </summary>
        internal static string SecondCash {
            get {
                return ResourceManager.GetString("SecondCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число выплаты аванса:.
        /// </summary>
        internal static string SecondPartDate {
            get {
                return ResourceManager.GetString("SecondPartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплаты с аванса, руб..
        /// </summary>
        internal static string SecondPay {
            get {
                return ResourceManager.GetString("SecondPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовой баланс, руб.:.
        /// </summary>
        internal static string YearBalance {
            get {
                return ResourceManager.GetString("YearBalance", resourceCulture);
            }
        }
    }
}
